# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-01-14 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pat_img',
        ),
    ]
