# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-01-14 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0003_patient_pat_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='symptoms',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
