# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-01-16 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0004_patient_symptoms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medrecord',
            old_name='gender',
            new_name='report',
        ),
    ]
